sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSFoawEzCLB4GqpZKme
    access-key-secret: ulUxKtIYejkHQ7jdfMexuWgL5oC7YN
    bucket-name: sky-itcast-wr
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxac14b777425e1ab2
    secret: 04704bd994855b037f8378f6b63629bb
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://1081c81.r16.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://1081c81.r16.cpolar.top/notify/refundSuccess